### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by broad-well** [PreMatch/PreMatch#1]
* [ ] EnrichingStudents integration
* [ ] Separate semesters
* [x] Responsive
* [x] Lunch
* [x] ScheduleBot integration
* [x] App
  * [x] Bundle widget
  * [ ] Bundle iMessage app
  * [ ] Siri integration (LUIS)
* [ ] Android App
  * [ ] Bundle widget
* [ ] Legal protection
  * [ ] Privacy Policy
  * [ ] Terms of Service
  * [ ] Ensure users agree to all of the above

### In the Near Future...
* [ ] Read schedule from PDF
